(defun c:AP()
 (defun excel(cota)
   (setq archivo (open "C:\\Users\\usuario\\Desktop\\lisp" "a"))
   (write-line "hola pacheco" archivo)
   (close archvo)
 	
    )
  (setq valor (getint "cantidad de cotas a tomar: "))
  (setq test 1)
  (while (<= test valor)
  (setq pto1(getpoint "\n dame un punto"))
  (setq pto2(getpoint "\n dame otro punto"))
  (setq distancia (distance pto1 pto2))
  (excel distancia)
  (setq test (1+ test))
)
)